curl --request GET --header "content-type:application/json" https://fantasy-predictor.appspot.com/_ah/api/players/v1/5654600029831168
curl --request GET --header "content-type:application/json" https://fantasy-predictor.appspot.com/_ah/api/players/v1/_?pageSize=5\&filter=season%3D2020-21
curl --request PUT --header "content-type:application/json" --data '{"aka": "deleted", "name": "Delete", "playerId": 69}' https://fantasy-predictor.appspot.com/_ah/api/players/v1/5654600029831168?updateMask=aka,playerId,name
curl --request GET --header "content-type:application/json" https://fantasy-predictor.appspot.com/_ah/api/players/v1/5654600029831168
curl --request PUT --header "content-type:application/json" --data '{"aka": "delete"}' https://fantasy-predictor.appspot.com/_ah/api/players/v1/5654600029831168?updateMask=aka

curl --request GET --header "content-type:application/json" https://fantasy-predictor.appspot.com/_ah/api/playerDays/v1/_?filter=date%3D2021-05-17
curl --request POST --header "content-type:application/json" --data '{"date":"2021-05-17","lowDataWarn":false,"opponent":"MEM","fantasySiteInfos":[],"name":"Juan Toscano-Anderson","team":"GSW","id":0,"playerId":0}' https://fantasy-predictor.appspot.com/_ah/api/playerDays/v1/echo
curl --request POST --header "content-type:application/json" --data '{"date":"2021-05-17","lowDataWarn":false,"opponent":"MEM","fantasySiteInfos":[{"fantasySite":"fanduel","projections":[{"projected":22.76,"basis":"RotoG Proj"},{"projected":6.2608,"basis":"RotoG Floor"},{"projected":32.422,"basis":"RotoG Ceil"}],"actual":0,"cost":15000,"positions":["PF","C"]},{"fantasySite":"draftkings","projections":[{"projected":22.76,"basis":"RotoG Proj"},{"projected":6.2608,"basis":"RotoG Floor"},{"projected":32.422,"basis":"RotoG Ceil"}],"actual":0,"cost":15000,"positions":["PF","C"]}],"name":"Juan Toscano-Anderson","team":"GSW","id":0,"playerId":0}' https://fantasy-predictor.appspot.com/_ah/api/playerDays/v1/echo
curl --request POST --header "content-type:application/json" --data '{"date":"2021-05-17","lowDataWarn":false,"opponent":"MEM","fantasySiteInfos":[{"fantasySite":"fanduel","projections":[{"projected":22.76,"basis":"RotoG Proj"},{"projected":6.2608,"basis":"RotoG Floor"},{"projected":32.422,"basis":"RotoG Ceil"}],"actual":0,"cost":15000,"positions":["PF","C"]},{"fantasySite":"draftkings","projections":[{"projected":22.76,"basis":"RotoG Proj"},{"projected":6.2608,"basis":"RotoG Floor"},{"projected":32.422,"basis":"RotoG Ceil"}],"actual":0,"cost":15000,"positions":["PF","C"]}],"name":"Juan Toscano-Anderson","team":"GSW","id":0,"playerId":0}' https://fantasy-predictor.appspot.com/_ah/api/playerDays/v1/_
curl --request GET --header "content-type:application/json" https://fantasy-predictor.appspot.com/_ah/api/playerDays/v1/_?filter=date%3D2021-05-17